#!/usr/bin/env bash
# After a successful ./build.sh on an H618 SDK with the 64-bit porting
# patches applied, copy the freshly-generated VNDK ABI dumps from the
# Soong intermediate tree into prebuilts/ and commit them. Idempotent.
#
# Usage:   ./regenerate-abi.sh PATH_TO_SDK_ROOT
# Example: ./regenerate-abi.sh /home/user/h618-android12.0
#
# Why this exists:
#   ./build.sh regenerates libstagefright_foundation.so.lsdump for both
#   arm and arm64 variants as a side effect of compiling the source,
#   but only inside out/soong/.intermediates/.  The abidiff step in
#   the next build then compares those fresh dumps against the tracked
#   prebuilts/.../libstagefright_foundation.so.lsdump and fails when
#   the contents differ.  Copying the fresh dumps in and committing
#   them keeps the tracked reference in sync.

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 PATH_TO_SDK_ROOT" >&2
    exit 1
fi

SDK="$1"
if [[ ! -x "$SDK/build.sh" ]]; then
    echo "error: $SDK does not look like a kickpi H618 SDK" >&2
    exit 1
fi

SRC_ARM64="$SDK/out/soong/.intermediates/frameworks/av/media/libstagefright/foundation/libstagefright_foundation/android_vendor.31_arm64_armv8-a_shared/libstagefright_foundation.so.lsdump"
SRC_ARM="$SDK/out/soong/.intermediates/frameworks/av/media/libstagefright/foundation/libstagefright_foundation/android_vendor.31_arm_armv8-a_shared/libstagefright_foundation.so.lsdump"

DST_ARM64="$SDK/prebuilts/abi-dumps/vndk/31/64/arm64_armv8-a/source-based/libstagefright_foundation.so.lsdump"
DST_ARM="$SDK/prebuilts/abi-dumps/vndk/31/64/arm_armv8-a/source-based/libstagefright_foundation.so.lsdump"

# Track two kinds of "missing":
#   - DST missing = something is structurally wrong (the tracked reference
#     should always exist); bail out.
#   - SRC missing = the build hasn't produced this variant's lsdump yet.
#     This is the normal state after build #1 — abidiff for arm64 fails
#     and aborts the build before Soong ever compiles the arm32 variant.
#     Handle each variant independently: copy + commit whichever SRC is
#     present, skip + warn about whichever SRC is missing.
DST_MISSING=0
for f in "$DST_ARM64" "$DST_ARM"; do
    if [[ ! -f "$f" ]]; then
        echo "error: missing tracked reference $f" >&2
        DST_MISSING=1
    fi
done
if [[ "$DST_MISSING" -ne 0 ]]; then
    echo "The prebuilts/.../libstagefright_foundation.so.lsdump reference" >&2
    echo "files should always exist.  Did a previous run of this script delete them?" >&2
    exit 1
fi

cd "$SDK"

UPDATED=0

# arm64 variant
if [[ -f "$SRC_ARM64" ]]; then
    if ! cmp -s "$SRC_ARM64" "$DST_ARM64"; then
        cp -f "$SRC_ARM64" "$DST_ARM64"
        git add "$DST_ARM64"
        echo "arm64 lsdump updated."
        UPDATED=1
    else
        echo "arm64 lsdump unchanged."
    fi
else
    echo "warning: $SRC_ARM64 not found — arm64 variant not built yet." >&2
    echo "         (Normal after build #1; will be produced on the next build.)" >&2
fi

# 32-bit variant
if [[ -f "$SRC_ARM" ]]; then
    if ! cmp -s "$SRC_ARM" "$DST_ARM"; then
        cp -f "$SRC_ARM" "$DST_ARM"
        git add "$DST_ARM"
        echo "32-bit lsdump updated."
        UPDATED=1
    else
        echo "32-bit lsdump unchanged."
    fi
else
    echo "warning: $SRC_ARM not found — 32-bit variant not built yet." >&2
    echo "         (Normal after build #1, because abidiff for arm64 fails" >&2
    echo "         and aborts the build before Soong compiles the arm32" >&2
    echo "         variant.  Re-run ./build.sh, then re-run this script.)" >&2
fi

if [[ "$UPDATED" -eq 0 ]]; then
    if [[ ! -f "$SRC_ARM64" && ! -f "$SRC_ARM" ]]; then
        echo "Neither variant's source lsdump was present, so there is" >&2
        echo "nothing to copy.  Did the build run at least once?" >&2
        exit 1
    fi
    echo "Nothing to commit."
    exit 0
fi

git diff --cached --stat
git commit -m "abi: regenerate VNDK arm64 + 32-bit libstagefright_foundation baselines

Auto-regenerated by h618-arm64-patch/regenerate-abi.sh after a clean
./build.sh.  The same C++ sources now compile on aarch64 (and again
on arm) into slightly different ELFs, so the source-based lsdumps
need to be refreshed.  The build's abidiff step accepts the new
content with -allow-unreferenced-changes."